### PR TITLE
#160578604 Fix Travis Deploy With Long Term Token

### PR DESCRIPTION
**Pull request by davenjeru**
#### What does this PR do?
 - Fixes the travis deploy error.
#### Description of Task to be completed?
 - Use `travis encrypt` to encrypt a long-term Heroku authentication token. This should enable automatic deploys after tests pass.

#### How should this be manually tested?
 Check [this](https://travis-ci.org/andela/ah-scorpion-frontend/builds/429929423#L3875) TravisCI build. The authentication should have succeeded.
#### Any background context you want to provide?
- It is difficult to manually test this PR. When Travis passes, the authentication to Heroku should succeed and a deploy should be made.
#### What are the relevant pivotal tracker stories?
[#160578604](https://www.pivotaltracker.com/story/show/160578604)

### CODE REVIEW

**Comment by kipropbrian** [comment]
Should this be part of the PR message? `Signed-off-by: davenjeru dave.njeru@andela.com`

**Review by hoslack — APPROVED** [review]
Great work, I would recommend that you document exactly what you did while adding the config to travis for future reference

**Review by RuthNjeri — APPROVED** [review]

**Comment by davenjeru** [comment]
@hoslack Please refer to this [thread](https://andela.slack.com/archives/GBT96054Y/p1535736753000100?thread_ts=1535736753.000100&cid=GBT96054Y)

**Comment by davenjeru** [comment]
@kipropbrian The sign-off should not be part of the PR description. It is normally added in commit messages by WebStorm.

**Review by lennykioko — APPROVED** [review]
Nice stuff

**Pull request merged**
