### PR TITLE
#160206226 Deploy to Heroku

### PR DESCRIPTION
**Pull request by davenjeru**
#### What does this PR do?
- Deploys the Authors Haven frontend to Heroku.

#### Description of tasks completed
- Edited the [.travis.yml](https://github.com/andela/ah-scorpion-frontend/blob/ch-deploy-to-heroku-160206226/.travis.yml) to add `deploy`
  - `provider: heroku` The provider is [Heroku](https://heroku.com)
  - In the code below, one has to provide an encrypted authenticaion token provided by heroku.
     ```
     api_key:
       secure: [ENCRYPTED TOKEN HERE]
     ```
  - `strategy: api` Uses the [Heroku API](https://devcenter.heroku.com/articles/platform-api-reference) to deploy
  - The code below specifies the branch to be deployed
     ```
     app:
       develop: authors-haven-frontend
       demo: authors-haven-dev
     ```
     If the develop branch triggers the build then the app will be deployed to [authors-haven-frontend](https://authors-haven-frontend.herokuapp.com)
     If the demo branch triggers the build then the app will be deployed to [authors-haven-dev](https://authors-haven-dev.herokuapp.com)
  - `skip_cleanup: true` Travis will not stash changes and therefore will send the build directory
- Remove the `npm install`, `npm test` lines from the .travis.yml. This is because:
  - TravisCI runs `npm ci` which takes care of `npm install` for us.
  - The line `npm test -- --coverage` takes care of the tests with the coverage so `npm test` would be redundant

#### How can this PR be manually tested
- Visit https://authors-haven-frontend.herokuapp.com and it should show a page.
- Examine the Travis build [here](https://travis-ci.org/andela/ah-scorpion-frontend/builds/423152763#L3309) to view the deploy process after testing

#### What are the related PR stories
- [#160206226](https://www.pivotaltracker.com/story/show/160206226)

### CODE REVIEW

**Comment by davenjeru** [comment]
Pull request closed for further research.

**Comment by davenjeru** [comment]
I had to close the pull request because deployments cannot be done by travis if the build is triggered by a pull request. Now that it's over, I can re-open the pull request.

**Review by RuthNjeri — APPROVED** [review]
The link to the Heroku app works! Good job removing the redundant lines on the Travis file.

**Review by hoslack — APPROVED** [review]
Great job on the initiative and work.

**Comment by zakhusayn** [comment]
👍🏽Great work.

**Review by lennykioko — APPROVED** [review]
Good job. You could work on deploying the build version of our app for better performance.

**Pull request merged**
