### PR TITLE
#160345391 Protect Dashboard Route

### PR DESCRIPTION
**Pull request by zakhusayn**
#### What does this PR do?
- Protect authorize route - Dashboard
#### Description of Task to be completed?
- Protect Dashboard Route
#### How should this be manually tested?
- Clone this repository and branch to `ch-Protect-Dashboard-16034539`
- Run your local-server `npm start -s`
- Access `localhost:3000/dashboard` you should be redirected back to login page.
- Try to login authorize user and see if you can access the route
#### What are the relevant pivotal tracker stories?
[#160345391](https://www.pivotaltracker.com/story/show/160345391)

### CODE REVIEW

**Review by munyili-samuel — CHANGES_REQUESTED** [review]
@blac-siren Please rename your PR to adhere to Git naming conventions

**Comment by RuthNjeri** [comment]
Hey Zack, you have named your branch wrongly in the PR description. It should be `ch-Protect-Dashboard-160345391`

**Review by hoslack — APPROVED** [review]
The PR works fine. Great job there Zac. I would wish that it is added to the project so that we use it to develop and protect some of our private routes. Kudos!

**Review by RuthNjeri — CHANGES_REQUESTED** [review]
Hi Zak,
In your `App.js` file you have imported `PrivateRoute` as a named export and exported it as default in the `PrivateRoute.js` file. You can remove the `{}` to show that it is exported as a default.

**Review by lennykioko — APPROVED** [review]
Tested and works perfectly fine.

**Review by davenjeru — APPROVED** [review]
I have tested the PR with @munyili-samuel and it works well. For a protected route, instead of using the `<Route/>` component, we should use the `<PrivateRoute/>`

**Review by RuthNjeri — APPROVED** [review]

**Review by munyili-samuel — APPROVED** [review]
Working well. Thumbs up

**Pull request merged**
