### PR TITLE
#160209202 Add a Pull Request Template File

### PR DESCRIPTION
**Pull request by RuthNjeri**
#### What does this PR do?
Adds a pull request template file.
#### Description of Task to be completed?
Add the correct format for writing Pull Requests in the repo.
#### How should this be manually tested?
When this branch is merged into the default branch, it will begin working.
#### Any background context you want to provide?
None.
#### What are the relevant pivotal tracker stories?
[160209202](https://www.pivotaltracker.com/story/show/160209202)

### CODE REVIEW

**Review by lennykioko — APPROVED** [review]
Nice job.

**Review by davenjeru — APPROVED** [review]
I have tested it with a different repository and t works.

**Review by hoslack — APPROVED** [review]
Great job.

**Review by zakhusayn — APPROVED** [review]
👍🏽Good Job

**Pull request merged**
