### PR TITLE
#159993331 Set Up Travis on The Project

### PR DESCRIPTION
**Pull request by RuthNjeri**
#### What does this PR do?
It adds a `.travis.yml` file to enable Travis integration.

#### Description of Task to be completed?
1.  Add a .travis.yml file in the root folder.
2. Add a Travis badge on the README file.

#### How should this be manually tested?
1. Clone the project by running `git clone https://github.com/andela/ah-scorpion-frontend.git` 
2. Switch to `git checkout ch-set-up-travis-159993331` on the Terminal.
3. Make any changes and push to Github, it will trigger a Travis build.

#### What are the relevant pivotal tracker stories?
[#159993331](https://www.pivotaltracker.com/story/show/159993331)

### CODE REVIEW

**Review by lennykioko — APPROVED** [review]
The integration works well. Nice work.

**Review by hoslack — APPROVED** [review]

**Comment by munyili-samuel** [comment]
I have followed the test instructions but the number of builds showing on Travis has not increased. The last build shown is not part of what I have done. See this screenshot:
screen shot 2018-08-28 at 13 41 27

**Note** I have pushed to a new branch

**Comment by davenjeru** [comment]
@munyili-samuel I can't see the screenshot...

**Comment by munyili-samuel** [comment]
@davenjeru I have updated the comment. The screenshot should be visible now

**Review by munyili-samuel — APPROVED** [review]
After the commit `[ch #59993331]remove whitespace in travis.yml file` the build is now being triggered after a commit is pushed

**Pull request merged**
